algoritmo "011"
var
    num1, num2, num3: real
inicio
    escreva("Digite numero 1: ")
    leia(num1)
    escreva("Digite numero 2: ")
    leia(num2)
    escreva("Digite numero 3: ")
    leia(num3)
    escreval("Primeiro passo:", num1, " *", num2, " =", num1 * num2)
    escreval("Segundo passo:", num1 * num2, " *", num3, " =", num1 * num2 * num3)
    escreval("Final:", num1 * num2 * num3)

fimalgoritmo