algoritmo "??"
var
    n1: inteiro
    n2: inteiro
    b1: logico
    b2: logico
inicio
    escreva("Primeiro Numero: ")
    leia (n1)
    escreva("Segundo Numero: ")
    leia (n2)
    b1 <- n1 mod 2 = 0
    b2 <- n2 mod 2 = 0

    escreval("O Primeiro é par: ", b1)
    escreval("O Segundo é par: ", b2)
    escreval("Resto da divisão inteira por 2 do primeiro:", n1 mod 2)
    escreval("Resto da divisão inteira por 2 do segundo:", n2 mod 2)

fimalgoritmo