algoritmo "??"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

i, input: inteiro

inicio

i <- 1
escreva ("Escolha um numero: ")
leia (input)
enquanto (i <= 10) faca
    escreval (input, " * ", i, " = ", input * i)
    i <- i + 1
fimenquanto

fimalgoritmo